import { useEffect, useState } from "react";
import { PanelShell } from "../../panel/layout/PanelShell";
import "./trainer-availability.css";
type Slot = { id: string; startsAt: string; endsAt: string; timezone: string; capacity: number; status: string };
export function TrainerAvailabilityPage({ user }: { user: { id: string; name: string; email: string } }) {
  const [slots, setSlots] = useState<Slot[]>([]); const [status, setStatus] = useState("loading"); const [message, setMessage] = useState("");
  const load = () => { setStatus("loading"); fetch("/api/trainer/availability", { credentials: "same-origin" }).then(async (r) => { if (!r.ok) throw Error(); setSlots((await r.json()).slots); setStatus("ready"); }).catch(() => setStatus("error")); };
  useEffect(load, []);
  const addSlot = async () => { const start = new Date(Date.now() + 2 * 60 * 60 * 1000); start.setMinutes(0, 0, 0); const end = new Date(start.getTime() + 60 * 60 * 1000); const response = await fetch("/api/trainer/availability", { method: "PATCH", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ startsAt: start.toISOString(), endsAt: end.toISOString(), capacity: 1 }) }); setMessage(response.ok ? "Müsaitlik aralığı kaydedildi." : response.status === 409 ? "Bu saat çakışıyor." : "Müsaitlik kaydedilemedi."); if (response.ok) load(); };
  return <PanelShell user={user}><main className="trainer-availability-page"><p className="availability-breadcrumb">Ana Sayfa <span>›</span> Müsaitlik Takvimim</p><div className="availability-heading"><div><h2>Müsaitlik Takvimim</h2><p>Gelecekte verebileceğiniz ders saatlerini yönetin.</p></div><button type="button" onClick={addSlot}>+ Yeni Müsaitlik Ekle</button></div>{message && <p role="status" className="availability-message">{message}</p>}{status === "loading" && <div role="status">Müsaitlikler yükleniyor…</div>}{status === "error" && <div role="alert">Müsaitlikler yüklenemedi. <button onClick={load}>Tekrar dene</button></div>}{status === "ready" && !slots.length && <div className="availability-empty"><h3>Henüz müsaitlik aralığı eklemediniz</h3><p>Yeni bir saat ekleyerek başlayabilirsiniz.</p></div>}{status === "ready" && slots.length > 0 && <div className="availability-list" aria-label="Müsaitlik aralıkları">{slots.map((slot) => <article key={slot.id}><strong>{new Date(slot.startsAt).toLocaleDateString("tr-TR", { weekday: "long", day: "numeric", month: "long" })}</strong><span>{new Date(slot.startsAt).toLocaleTimeString("tr-TR", { hour: "2-digit", minute: "2-digit" })} – {new Date(slot.endsAt).toLocaleTimeString("tr-TR", { hour: "2-digit", minute: "2-digit" })}</span><small>{slot.status === "OPEN" ? "Müsait" : slot.status} · Kapasite {slot.capacity}</small></article>)}</div>}</main></PanelShell>;
}
