CREATE TYPE "public"."package_catalog_status" AS ENUM('DRAFT','PUBLISHED','RETIRED');--> statement-breakpoint
CREATE TYPE "public"."package_delivery_mode" AS ENUM('SELF_PACED','TRAINER_LED','HYBRID');--> statement-breakpoint
CREATE TABLE "packages" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"slug" text NOT NULL,"audience" "training_program_audience" NOT NULL,"status" "package_catalog_status" DEFAULT 'DRAFT' NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "packages_slug_unique" UNIQUE("slug"));--> statement-breakpoint
CREATE TABLE "package_versions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"package_id" uuid NOT NULL,"version_number" integer NOT NULL,"title" text NOT NULL,"description" text NOT NULL,"price_minor" integer,"currency" text,"status" "package_catalog_status" DEFAULT 'DRAFT' NOT NULL,"published_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "package_versions_package_version_uq" UNIQUE("package_id","version_number"));--> statement-breakpoint
CREATE TABLE "package_entitlement_definitions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"package_version_id" uuid NOT NULL,"training_program_id" uuid NOT NULL,"delivery_mode" "package_delivery_mode" NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "package_entitlement_definitions_version_program_uq" UNIQUE("package_version_id","training_program_id"));--> statement-breakpoint
ALTER TABLE "package_versions" ADD CONSTRAINT "package_versions_package_id_fk" FOREIGN KEY ("package_id") REFERENCES "public"."packages"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "package_entitlement_definitions" ADD CONSTRAINT "package_entitlement_definitions_version_fk" FOREIGN KEY ("package_version_id") REFERENCES "public"."package_versions"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "package_entitlement_definitions" ADD CONSTRAINT "package_entitlement_definitions_program_fk" FOREIGN KEY ("training_program_id") REFERENCES "public"."training_programs"("id") ON DELETE restrict;--> statement-breakpoint
CREATE INDEX "package_versions_published_idx" ON "package_versions" ("status");--> statement-breakpoint
