CREATE TYPE "public"."trainer_qualification_status" AS ENUM('ACTIVE','SUSPENDED','REVOKED');--> statement-breakpoint
CREATE TYPE "public"."trainer_assignment_request_status" AS ENUM('PENDING','ASSIGNED','CANCELLED');--> statement-breakpoint
CREATE TABLE "trainer_qualifications" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"trainer_user_id" uuid NOT NULL,"training_program_id" uuid NOT NULL,"status" "trainer_qualification_status" DEFAULT 'ACTIVE' NOT NULL,"qualified_at" timestamptz DEFAULT now() NOT NULL,"revoked_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "trainer_qualifications_trainer_program_uq" UNIQUE("trainer_user_id","training_program_id"));--> statement-breakpoint
CREATE TABLE "trainer_assignment_requests" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"enrollment_id" uuid NOT NULL,"status" "trainer_assignment_request_status" DEFAULT 'PENDING' NOT NULL,"trainer_assignment_id" uuid,"requested_at" timestamptz DEFAULT now() NOT NULL,"assigned_at" timestamptz,"cancelled_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);--> statement-breakpoint
ALTER TABLE "trainer_qualifications" ADD CONSTRAINT "trainer_qualifications_trainer_fk" FOREIGN KEY ("trainer_user_id") REFERENCES "public"."platform_users"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "trainer_qualifications" ADD CONSTRAINT "trainer_qualifications_program_fk" FOREIGN KEY ("training_program_id") REFERENCES "public"."training_programs"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "trainer_assignment_requests" ADD CONSTRAINT "trainer_assignment_requests_enrollment_fk" FOREIGN KEY ("enrollment_id") REFERENCES "public"."enrollments"("id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "trainer_assignment_requests" ADD CONSTRAINT "trainer_assignment_requests_assignment_fk" FOREIGN KEY ("trainer_assignment_id") REFERENCES "public"."trainer_assignments"("id") ON DELETE restrict;--> statement-breakpoint
CREATE UNIQUE INDEX "trainer_assignment_requests_pending_uq" ON "trainer_assignment_requests" ("enrollment_id") WHERE "status"='PENDING';--> statement-breakpoint
