import { useEffect, useState } from "react";
import { PanelShell } from "../../panel/layout/PanelShell";
import "./trainer-earnings.css";

type Entry = { id: string; type: string; status: string; amountMinor: number; currency: string; description: string; occurredAt: string };
type Payload = { currency: string; summary: { earnedMinor: number; paidMinor: number; heldMinor: number; pendingMinor: number }; entries: Entry[]; payout: string };
const money = (minor: number, currency: string) => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(minor / 100);
const labels: Record<string, string> = { SESSION: "Ders / oturum", BONUS: "Prim", ADJUSTMENT: "Düzeltme" };

export function TrainerEarningsPage({ user }: { user: { id: string; name: string; email: string } }) {
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [payload, setPayload] = useState<Payload | null>(null);
  const load = () => { setState("loading"); fetch("/api/trainer/earnings", { credentials: "same-origin" }).then(async (r) => { if (!r.ok) throw Error(); setPayload(await r.json()); setState("ready"); }).catch(() => setState("error")); };
  useEffect(load, []);
  return <PanelShell user={user}><main className="trainer-earnings-page"><div className="earnings-heading"><div><h2>Kazançlarım</h2><p>Gerçekleşen ve bekleyen eğitmen kazançlarınızı buradan takip edebilirsiniz.</p></div><div className="earnings-note">Ödeme altyapısı<br /><strong>sonraki fazda</strong> etkinleşecek.</div></div>{state === "loading" && <div className="earnings-state" role="status">Kazançlar yükleniyor…</div>}{state === "error" && <div className="earnings-state"><h3>Kazançlar yüklenemedi</h3><button type="button" onClick={load}>Tekrar dene</button></div>}{state === "ready" && payload && <><div className="earnings-summary"><article><span>Toplam hak ediş</span><strong>{money(payload.summary.earnedMinor, payload.currency)}</strong></article><article><span>Ödenen tutar</span><strong>{money(payload.summary.paidMinor, payload.currency)}</strong></article><article><span>Kalan bakiye</span><strong>{money(payload.summary.pendingMinor, payload.currency)}</strong></article></div><section className="earnings-card"><h3>Hareketler</h3>{!payload.entries.length ? <p className="earnings-empty">Henüz kayıtlı bir kazanç hareketi yok.</p> : <div className="earnings-table-wrap"><table><thead><tr><th scope="col">Tarih</th><th scope="col">Tür</th><th scope="col">Açıklama</th><th scope="col">Durum</th><th scope="col">Tutar</th></tr></thead><tbody>{payload.entries.map((entry) => <tr key={entry.id}><td>{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium" }).format(new Date(entry.occurredAt))}</td><td>{labels[entry.type] || "Diğer kazanç"}</td><td>{entry.description}</td><td><span className={`earning-status ${entry.status.toLowerCase()}`}>{entry.status === "PAID" ? "Ödendi" : entry.status === "HELD" ? "Bekliyor" : entry.status === "REVERSED" ? "İptal" : "Hak edildi"}</span></td><td>{money(entry.amountMinor, entry.currency)}</td></tr>)}</tbody></table></div>}<p className="earnings-footnote">Ödeme talebi ve banka aktarımı bu fazda kullanılabilir değildir.</p></section></>}</main></PanelShell>;
}
