import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { StudentPanelShell } from "./StudentPanelShell";
import "./student-portal.css";

type Profile = { firstName: string; lastName: string; dateOfBirth: string; grade: string; classBranch: string; school: string; schoolType: string; city: string; district: string; email: string; phone: string; guardianRelation: string; guardianName: string; guardianPhone: string; guardianEmail: string; addressLine: string; postalCode: string; marketingConsent?: boolean; photoStorageKey?: string | null; photoUrl?: string | null };
const empty: Profile = { firstName: "", lastName: "", dateOfBirth: "", grade: "", classBranch: "", school: "", schoolType: "", city: "", district: "", email: "", phone: "", guardianRelation: "", guardianName: "", guardianPhone: "", guardianEmail: "", addressLine: "", postalCode: "", marketingConsent: false };
const grades = ["Anaokulu", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"];
const tabs = [
  ["personal", "Kişisel Bilgiler"],
  ["education", "Eğitim Bilgileri"],
  ["guardian", "Veli ve İletişim"],
  ["address", "Adres"],
] as const;
type TabId = typeof tabs[number][0];

export function StudentProfilePage({ guardian = false, user = { name: "Öğrenci" } }: { guardian?: boolean; user?: { name: string; email?: string } }) {
  const [profile, setProfile] = useState<Profile>(empty);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [message, setMessage] = useState("");
  const [tab, setTab] = useState<TabId>("personal");
  const [photoDataUrl, setPhotoDataUrl] = useState<string | null>(null);
  const [removePhoto, setRemovePhoto] = useState(false);
  const load = () => {
    setState("loading");
    const query = guardian ? `?studentProfileId=${encodeURIComponent(new URLSearchParams(window.location.search).get("studentProfileId") || "")}` : "";
    fetch(`/api/student/profile${query}`, { credentials: "same-origin" }).then(async (response) => { if (!response.ok) throw new Error(); const body = await response.json(); setProfile({ ...empty, ...body.profile }); setState("ready"); }).catch(() => { setMessage("Profil verileri yüklenemedi."); setState("error"); });
  };
  useEffect(() => { load(); }, []);
  const update = (key: keyof Profile, value: string) => setProfile((current) => ({ ...current, [key]: value }));
  const choosePhoto = (file?: File) => { if (!file || !/^image\/(jpeg|png|webp)$/u.test(file.type) || file.size > 2 * 1024 * 1024) { setMessage("JPG, PNG veya WebP ve en fazla 2 MB kullanın."); return; } const reader = new FileReader(); reader.onload = () => { setPhotoDataUrl(String(reader.result)); setRemovePhoto(false); }; reader.readAsDataURL(file); };
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(""); const response = await fetch("/api/student/profile", { method: "PATCH", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...profile, ...(photoDataUrl ? { photoDataUrl } : {}), ...(removePhoto ? { removePhoto: true } : {}) }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.errors ? Object.values(body.errors).filter(Boolean).join(" ") : "Profil kaydedilemedi."); return; } setProfile({ ...profile, ...body.profile }); setPhotoDataUrl(null); setRemovePhoto(false); setMessage("Profiliniz kaydedildi."); };
  const initials = `${(profile.firstName || user.name).charAt(0)}${(profile.lastName || user.name.split(" ").at(-1) || "").charAt(0)}`.toLocaleUpperCase("tr-TR");
  const panelFor = (id: TabId) => {
    if (id === "personal") return <div className="student-profile-grid"><Field label="Ad" value={profile.firstName} required readOnly={guardian} onChange={(value) => update("firstName", value)} /><Field label="Soyad" value={profile.lastName} required readOnly={guardian} onChange={(value) => update("lastName", value)} /><Field label="Doğum tarihi" type="date" value={profile.dateOfBirth} readOnly={guardian} onChange={(value) => update("dateOfBirth", value)} /><Field label="E-posta" type="email" value={profile.email} readOnly onChange={() => {}} /><Field label="Telefon" type="tel" value={profile.phone} readOnly={guardian} onChange={(value) => update("phone", value)} /><label className="student-profile-field-wide">Profil fotoğrafı<input type="file" disabled={guardian} accept="image/jpeg,image/png,image/webp" onChange={(event) => choosePhoto(event.target.files?.[0])} />{!guardian && (profile.photoStorageKey || photoDataUrl) && <button type="button" className="student-profile-secondary" onClick={() => { setRemovePhoto(true); setPhotoDataUrl(null); setProfile({ ...profile, photoStorageKey: null, photoUrl: null }); }}>Fotoğrafı kaldır</button>}</label></div>;
    if (id === "education") return <div className="student-profile-grid"><label>Sınıf<select disabled={guardian} value={profile.grade} onChange={(event) => update("grade", event.target.value)}><option value="">Seçin</option>{grades.map((grade) => <option key={grade} value={grade}>{grade}</option>)}</select></label><Field label="Şube" value={profile.classBranch} readOnly={guardian} onChange={(value) => update("classBranch", value)} /><Field label="Okul" value={profile.school} readOnly={guardian} onChange={(value) => update("school", value)} /><Field label="Okul türü" value={profile.schoolType} readOnly={guardian} onChange={(value) => update("schoolType", value)} /></div>;
    if (id === "guardian") return <div className="student-profile-grid"><Field label="Veli / yakınlık" value={profile.guardianRelation} readOnly={guardian} onChange={(value) => update("guardianRelation", value)} /><Field label="Veli adı" value={profile.guardianName} readOnly={guardian} onChange={(value) => update("guardianName", value)} /><Field label="Veli telefonu" type="tel" value={profile.guardianPhone} readOnly={guardian} onChange={(value) => update("guardianPhone", value)} /><Field label="Veli e-postası" type="email" value={profile.guardianEmail} readOnly={guardian} onChange={(value) => update("guardianEmail", value)} /><Field label="Öğrenci telefonu" type="tel" value={profile.phone} readOnly={guardian} onChange={(value) => update("phone", value)} /><Field label="Öğrenci e-postası" type="email" value={profile.email} readOnly onChange={() => {}} /><p className="student-profile-helper student-profile-field-wide">Veli iletişim bilgileri yalnızca bu öğrenci hesabının sahibi tarafından güncellenebilir.</p></div>;
    return <div className="student-profile-grid"><label className="student-profile-field-wide">Adres ayrıntısı<textarea value={profile.addressLine || ""} readOnly={guardian} onChange={(event) => update("addressLine", event.target.value)} /></label><Field label="Posta kodu" value={profile.postalCode} readOnly={guardian} onChange={(value) => update("postalCode", value)} /><Field label="Şehir" value={profile.city} readOnly={guardian} onChange={(value) => update("city", value)} /><Field label="İlçe" value={profile.district} readOnly={guardian} onChange={(value) => update("district", value)} /><p className="student-profile-helper student-profile-field-wide">Şehir ve ilçe bilgileri profilinizle birlikte kaydedilir. Sokak adresi, teslimat sırasında sipariş adresinden alınır.</p></div>;
  };
  if (state === "loading") return <StudentPanelShell user={user} guardian><div className="student-portal__state" role="status">Profil yükleniyor…</div></StudentPanelShell>;
  return <StudentPanelShell user={user} guardian><div className="student-portal__hero"><div><h1>Profilim</h1><p>Kişisel, eğitim, veli ve adres bilgilerinizi ayrı sekmelerde güncel tutun.</p></div><div className="student-profile-avatar-wrap">{photoDataUrl || profile.photoUrl ? <img className="student-profile-avatar" src={photoDataUrl || `${profile.photoUrl}?v=${encodeURIComponent(profile.photoStorageKey || "")}`} alt="Profil fotoğrafı" /> : <div className="student-profile-avatar" aria-hidden="true">{initials}</div>}</div></div>{message && <p className="student-portal__banner" role="status">{message}</p>}{state === "error" ? <div className="student-portal__state"><h3>Profil yüklenemedi</h3><button type="button" onClick={load}>Tekrar dene</button></div> : <form onSubmit={(event) => void save(event)} className="student-profile-form"><section className="student-portal__card"><div className="student-profile-tabs" role="tablist" aria-label="Profil bölümleri">{tabs.map(([id, label], index) => <button key={id} id={`student-profile-tab-${id}`} type="button" role="tab" aria-selected={tab === id} aria-controls={`student-profile-panel-${id}`} tabIndex={tab === id ? 0 : -1} className={tab === id ? "is-active" : ""} onClick={() => setTab(id)} onKeyDown={(event) => { if (event.key === "ArrowRight" || event.key === "ArrowDown") { event.preventDefault(); setTab(tabs[(index + 1) % tabs.length][0]); } if (event.key === "ArrowLeft" || event.key === "ArrowUp") { event.preventDefault(); setTab(tabs[(index + tabs.length - 1) % tabs.length][0]); } }}>{label}</button>)}</div><div id={`student-profile-panel-${tab}`} role="tabpanel" aria-labelledby={`student-profile-tab-${tab}`} className="student-profile-tab-panel"><h2>{tabs.find(([id]) => id === tab)?.[1]}</h2>{panelFor(tab)}</div></section>{!guardian && <button className="student-profile-submit" type="submit">Profilimi güncelle</button>}{guardian && <p className="student-profile-helper">Veli görünümünde öğrenci bilgileri yalnızca görüntülenir.</p>}</form>}</StudentPanelShell>;
}
function Field({ label, value, onChange, type = "text", required = false, readOnly = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; readOnly?: boolean }) { return <label>{label}<input required={required} type={type} readOnly={readOnly} value={value || ""} onChange={(event) => onChange(event.target.value)} /></label>; }
