import pg from "pg";
import { resolvePrincipal, requirePermission } from "../../src/server/auth/authorization.js";
const json=(res,status,body)=>{res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(body));};
const h=req=>new Headers(Object.entries(req.headers||{}).map(([k,v])=>[k,String(v)]));
async function read(req){let s="";for await(const c of req)s+=c;return s?JSON.parse(s):{};}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
export default async function handler(req,res){
  const p=await resolvePrincipal(h(req));if(!p)return json(res,401,{error:"UNAUTHENTICATED"});const denied=requirePermission(p,"trainer.training.read",{role:"TRAINER"});if(denied)return json(res,denied.status,denied.body);
  const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
  try{const url=new URL(req.url,"http://local");const enrollmentId=url.searchParams.get("enrollmentId")||String((await read(req).catch(()=>({}))).enrollmentId||"");if(!UUID.test(enrollmentId))return json(res,400,{error:"INVALID_ENROLLMENT_ID"});
    if(req.method==="GET"){const e=(await pool.query("select e.id,e.status,e.progress_percent as \"progressPercent\",e.created_at as \"startedAt\",e.completed_at as \"completedAt\",tp.id as \"trainingProgramId\",tp.title as \"programTitle\",u.display_name as \"studentName\" from enrollments e join training_programs tp on tp.id=e.training_program_id join platform_users u on u.id=e.student_user_id join trainer_assignments a on a.enrollment_id=e.id and a.trainer_user_id=$2 and a.status='ACTIVE' where e.id=$1",[enrollmentId,p.user.id])).rows[0];if(!e)return json(res,404,{error:"ENROLLMENT_NOT_FOUND"});const sessions=(await pool.query("select id,status,progress_percent as \"progressPercent\",notes,started_at as \"startedAt\",completed_at as \"completedAt\" from enrollment_sessions where enrollment_id=$1 order by created_at desc",[enrollmentId])).rows;return json(res,200,{enrollment:e,sessions});}
    if(req.method!=="PATCH"&&req.method!=="POST")return json(res,405,{error:"METHOD_NOT_ALLOWED"});const x=await read(req);const c=await pool.connect();try{await c.query("begin");const a=(await c.query("select a.id,e.status from trainer_assignments a join enrollments e on e.id=a.enrollment_id where a.enrollment_id=$1 and a.trainer_user_id=$2 and a.status='ACTIVE' for update",[enrollmentId,p.user.id])).rows[0];if(!a)throw Object.assign(new Error("TRAINER_ASSIGNMENT_NOT_FOUND"),{status:404});if(req.method==="PATCH"){const progress=Number(x.progressPercent);if(!Number.isSafeInteger(progress)||progress<0||progress>100)throw Object.assign(new Error("PROGRESS_INVALID"),{status:400});const status=progress===100?"COMPLETED":progress>0?"ACTIVE":"ACTIVE";await c.query("update enrollments set progress_percent=$1,status=$2,completed_at=case when $1=100 then coalesce(completed_at,now()) else completed_at end,updated_at=now() where id=$3",[progress,status,enrollmentId]);await c.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'education.progress.updated','enrollment',$2,'SUCCESS',gen_random_uuid(),$3)",[p.user.id,enrollmentId,JSON.stringify({progressPercent:progress})]);await c.query("commit");return json(res,200,{status,progressPercent:progress,completionRequired:progress===100});}
      const startedAt=x.startedAt||new Date().toISOString();const row=(await c.query("insert into enrollment_sessions(enrollment_id,assignment_id,trainer_user_id,status,progress_percent,notes,started_at,completed_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,status,progress_percent as \"progressPercent\",notes,started_at as \"startedAt\",completed_at as \"completedAt\"",[enrollmentId,a.id,p.user.id,String(x.status||"SCHEDULED"),Number(x.progressPercent||0),x.notes||null,startedAt,x.status==="COMPLETED"?new Date().toISOString():null])).rows[0];await c.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'education.session.recorded','enrollment_session',$2,'SUCCESS',gen_random_uuid(),$3)",[p.user.id,row.id,JSON.stringify({enrollmentId})]);await c.query("commit");return json(res,201,{session:row});
    }catch(e){try{await c.query("rollback")}catch{ /* preserve original error */ }return json(res,e.status||409,{error:e.code||e.message||"PROGRESS_UPDATE_FAILED"});}finally{c.release();}
  }catch{return json(res,503,{error:"PROGRESS_UNAVAILABLE"});}finally{await pool.end();}
}
