import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./admin-panel.css";
type Trainer={id:string;displayName:string;email:string;qualificationId:string|null;programTitle:string|null;qualificationStatus:string|null;source:string|null;reason:string|null};
type Program={id:string;title:string;slug:string};
const statusLabel:Record<string,string>={ACTIVE:"Yetkili",SUSPENDED:"Askıya alındı",REVOKED:"İptal edildi"}; const sourceLabel:Record<string,string>={ADMIN_GRANT:"Yönetici tarafından verildi",PACKAGE_COMPLETION:"Paket/eğitim tamamlama",LEGACY_IMPORT:"Eski sistem aktarımı"};
const searchText = (value: string) => value.toLocaleLowerCase("tr-TR");

export function AdminTrainersPage(){
  const [rows,setRows]=useState<Trainer[]>([]);const [programs,setPrograms]=useState<Program[]>([]);const [message,setMessage]=useState("");
  const [userSearch,setUserSearch]=useState("");const [programSearch,setProgramSearch]=useState("");
  const [form,setForm]=useState({userId:"",trainingProgramId:"",action:"grant",source:"ADMIN_GRANT",reason:""});
  const load=()=>fetch("/api/admin/trainers",{credentials:"same-origin"}).then(r=>r.json()).then(x=>{setRows(x.trainers||[]);setPrograms(x.trainingPrograms||[])}).catch(()=>setMessage("Eğitmen listesi yüklenemedi."));
  useEffect(()=>{void load()},[]);
  const uniqueRows=rows.filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i);
  const operationalRows=uniqueRows.filter((r)=>!r.email.toLocaleLowerCase("tr-TR").endsWith("@example.test"));
  const normalizedUserSearch=searchText(userSearch.trim());
  const filteredRows=operationalRows.filter((r)=>!normalizedUserSearch||searchText(`${r.displayName} ${r.email}`).includes(normalizedUserSearch));
  const normalizedProgramSearch=searchText(programSearch.trim());
  const filteredPrograms=programs.filter((p)=>!normalizedProgramSearch||searchText(p.title).includes(normalizedProgramSearch));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/admin/trainers",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));setMessage(r.ok?"Yetki güncellendi.":b.error||"İşlem başarısız.");if(r.ok)void load()};
  return <main className="platform-foundation-panel admin-panel"><nav aria-label="Yönetim paneli menüsü"><Link to="/panel/admin">Genel Bakış</Link><Link to="/panel/admin/atamalar">Eğitmen Atamaları</Link><Link to="/panel/admin/paketler">Paket Yönetimi</Link><Link to="/panel/admin/egitmenler" aria-current="page">Eğitmenler</Link></nav><h1>Eğitmen yetkileri</h1><p>Eğitmenleri ve program yetkilerini insan adıyla yönetin.</p>{message&&<p role="status">{message}</p>}<form className="panel-card admin-package-form" onSubmit={(e)=>void submit(e)}><h2>Yetki işlemi</h2><label htmlFor="admin-trainer-user-search">Kullanıcı ara<input id="admin-trainer-user-search" type="search" value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Ad veya e-posta" autoComplete="off" /></label><label htmlFor="admin-trainer-user">Kullanıcı seç<select id="admin-trainer-user" required value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Eğitmen seçin</option>{filteredRows.map(r=><option key={r.id} value={r.id}>{r.displayName} · {r.email}</option>)}</select></label><label htmlFor="admin-trainer-program-search">Program ara<input id="admin-trainer-program-search" type="search" value={programSearch} onChange={e=>setProgramSearch(e.target.value)} placeholder="Program adı" autoComplete="off" /></label><label htmlFor="admin-trainer-program">Program seç<select id="admin-trainer-program" required value={form.trainingProgramId} onChange={e=>setForm({...form,trainingProgramId:e.target.value})}><option value="">Program seçin</option>{filteredPrograms.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>İşlem<select value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value="grant">Yetkilendir</option><option value="reactivate">Yeniden etkinleştir</option><option value="suspend">Askıya al</option><option value="revoke">İptal et</option></select></label><label>Kaynak<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option value="ADMIN_GRANT">Yönetici tarafından verildi</option><option value="PACKAGE_COMPLETION">Paket/eğitim tamamlama</option><option value="LEGACY_IMPORT">Eski sistem aktarımı</option></select></label><label>Gerekçe<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button type="submit">İşlemi kaydet</button></form><section className="panel-card"><h2>Kayıtlı eğitmenler</h2><div className="admin-package-grid">{operationalRows.map((r)=><article className="admin-package-card" key={`${r.id}-${r.qualificationId||"none"}`}><h3>{r.displayName}</h3><p>{r.email}</p><p>{r.programTitle||"Program seçilmemiş"}</p><strong>{statusLabel[r.qualificationStatus||""]||"Yetki yok"}</strong>{r.source&&<small>{sourceLabel[r.source]||"Bilinmeyen kaynak"}{r.reason?` · ${r.reason}`:""}</small>}<Link to={`/panel/admin/egitmenler/${r.id}`}>Detay ve geçmiş</Link></article>)}</div></section></main>
}
