import { useEffect, useState } from "react";

const keys = [["GTM", "GTM_CONTAINER_ID"], ["GA4", "GA4_MEASUREMENT_ID"], ["Google Ads", "GOOGLE_ADS_ID"], ["Meta Pixel", "META_PIXEL_ID"], ["Meta CAPI", "META_CAPI_ACCESS_TOKEN"], ["TikTok Pixel", "TIKTOK_PIXEL_ID"], ["TikTok Events API", "TIKTOK_EVENTS_ACCESS_TOKEN"]] as const;
export function MeasurementPage() {
  const [consent, setConsent] = useState<any>(null);
  const [events, setEvents] = useState<any[]>([]);
  useEffect(() => { const update = () => { try { setConsent(JSON.parse(window.localStorage.getItem("fixoku_consent_preferences") || "null")); } catch { setConsent(null); } }; update(); window.addEventListener("fixoku:consent-updated", update); return () => window.removeEventListener("fixoku:consent-updated", update); }, []);
  useEffect(() => { const update = () => { const layer = Array.isArray((window as any).dataLayer) ? (window as any).dataLayer : []; setEvents(layer.slice(-20).filter((item: any) => item && typeof item === "object" && typeof item.event === "string").map((item: any) => ({ event: item.event, event_id: item.event_id, event_time: item.event_time, page: item.page_path, consent_state: item.consent_state }))); }; update(); const timer = window.setInterval(update, 500); return () => window.clearInterval(timer); }, []);
  return <main className="platform-foundation-panel admin-panel"><nav aria-label="Yönetim paneli menüsü"><a href="/panel/owner">Genel Bakış</a><a href="/panel/owner/e-posta-sablonlari">E-posta şablonları</a><a href="/panel/owner/olcumleme" aria-current="page">Ölçümleme</a></nav><h1>Ölçümleme</h1><p>Yalnızca güvenli yapılandırma özeti gösterilir; sırlar, tokenlar ve öğrenci verileri gösterilmez.</p><section className="admin-package-grid"><article className="admin-package-card"><h2>Onay sistemi</h2><p className="admin-status admin-status-published">Etkin · varsayılan kapalı</p><pre>{JSON.stringify(consent?.categories || { necessary: true, functional: false, analytics: false, advertising: false }, null, 2)}</pre></article>{keys.map(([label, key]) => <article className="admin-package-card" key={key}><h2>{label}</h2><p className="admin-status">Yapılandırma bekliyor</p><small>Teknik anahtar: {key} · değer gösterilmez</small></article>)}</section><section className="admin-package-card"><h2>Güvenli yerel olay günlüğü</h2><p>Yalnızca olay, kimlik, zaman, sayfa ve onay durumu tutulur. Sağlayıcılara gerçek olay gönderilmez.</p>{events.length ? <pre>{JSON.stringify(events, null, 2)}</pre> : <p>Henüz olay gönderilmedi.</p>}</section></main>;
}
