import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import "./admin-panel.css";

type FilterState = { from: string; to: string; packageId: string; trainerId: string; currency: string };
const EMPTY_FILTERS: FilterState = { from: "", to: "", packageId: "", trainerId: "", currency: "" };
const money = (minor: number | null | undefined, currency = "TRY") => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format((minor ?? 0) / 100);
const entryLabels: Record<string, string> = { ADJUSTMENT: "Düzeltme", SALE: "Satış", REFUND: "İade", PAYOUT: "Eğitmen ödemesi", SHIPPING: "Kargo", PRODUCT_COST: "Ürün maliyeti" };
const readFilters = (params: URLSearchParams): FilterState => ({ from: params.get("from") || "", to: params.get("to") || "", packageId: params.get("packageId") || "", trainerId: params.get("trainerId") || "", currency: (params.get("currency") || "").toUpperCase() });

export function OwnerFinancePage() {
  const [params, setParams] = useSearchParams();
  const [filters, setFilters] = useState<FilterState>(() => readFilters(params));
  const [d, setD] = useState<any>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [adjustment, setAdjustment] = useState({ entryType: "ADJUSTMENT", sourceType: "MANUAL", amountMinor: "", sourceId: "", note: "", currency: "TRY" });
  const query = useMemo(() => { const q = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && q.set(key, value)); return q.toString(); }, [filters]);
  useEffect(() => { const next = readFilters(params); setFilters((current) => JSON.stringify(current) === JSON.stringify(next) ? current : next); }, [params]);
  useEffect(() => { let active = true; setError(""); fetch(`/api/owner/finance${query ? `?${query}` : ""}`, { credentials: "same-origin" }).then(async (r) => { if (!r.ok) throw Error(); const body = await r.json(); if (active) setD(body); }).catch(() => active && setError("Finans verileri yalnızca Owner yetkisiyle ve temiz yerel veritabanından okunabilir.")); return () => { active = false; }; }, [query]);
  const setFilter = (key: keyof FilterState, value: string) => { const next = { ...filters, [key]: key === "currency" ? value.toUpperCase() : value }; setFilters(next); const q = new URLSearchParams(); Object.entries(next).forEach(([k, v]) => v && q.set(k, v)); setParams(q, { replace: true }); };
  const clearFilters = () => { setFilters(EMPTY_FILTERS); setParams({}, { replace: true }); };
  const exportCsv = () => { const q = new URLSearchParams(query); q.set("format", "csv"); window.location.assign(`/api/owner/finance?${q.toString()}`); };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/owner/finance", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...adjustment, amountMinor: Number(adjustment.amountMinor) }) }); const b = await r.json().catch(() => ({})); setMessage(r.ok ? "Finans düzeltmesi kaydedildi." : b.error || "Düzeltme kaydedilemedi."); if (r.ok) { setAdjustment({ ...adjustment, amountMinor: "", sourceId: "", note: "" }); setD(null); const response = await fetch(`/api/owner/finance${query ? `?${query}` : ""}`, { credentials: "same-origin" }); if (response.ok) setD(await response.json()); } };
  const metrics = d?.metrics || {};
  return <main className="platform-foundation-panel admin-panel"><nav aria-label="Yönetici menüsü"><Link to="/panel/owner">Genel bakış</Link><Link to="/panel/owner/finance" aria-current="page">Finans özeti</Link><Link to="/panel/owner/saglayicilar">Sağlayıcı durumu</Link><Link to="/panel/owner/olcumleme">Ölçümleme</Link><Link to="/panel/owner/e-posta-sablonlari">E-posta şablonları</Link><Link to="/panel/admin">Operasyon paneli</Link><Link to="/panel/bildirimler">Bildirimler</Link></nav><h1>Finans Özeti</h1><p>Operasyonel gelir, yükümlülük ve eğitmen ödemeleri görünümü. Statü muhasebesi değildir.</p>
    <section className="panel-card finance-filters" aria-label="Finans filtreleri"><h2>Filtreler</h2><div className="admin-finance-toolbar"><label>Başlangıç tarihi<input type="date" value={filters.from} onChange={(e) => setFilter("from", e.target.value)} /></label><label>Bitiş tarihi<input type="date" value={filters.to} onChange={(e) => setFilter("to", e.target.value)} /></label><label>Paket<select value={filters.packageId} onChange={(e) => setFilter("packageId", e.target.value)}><option value="">Tüm paketler</option>{(d?.packages || []).map((x: any) => <option key={x.packageId} value={x.packageId}>{x.title}</option>)}</select></label><label>Eğitmen<select value={filters.trainerId} onChange={(e) => setFilter("trainerId", e.target.value)}><option value="">Tüm eğitmenler</option>{(d?.trainers || []).map((x: any) => <option key={x.trainerId} value={x.trainerId}>{x.name}</option>)}</select></label><label>Para birimi<input value={filters.currency} onChange={(e) => setFilter("currency", e.target.value.slice(0, 3))} placeholder="TRY" maxLength={3} /></label></div><div className="finance-filter-actions"><button type="button" onClick={() => setParams(new URLSearchParams(query), { replace: true })}>Filtrele</button><button type="button" onClick={clearFilters}>Temizle</button><button type="button" onClick={exportCsv} disabled={!d}>CSV indir</button></div></section>
    {error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}{!d && !error && <p role="status">Finans verileri yükleniyor…</p>}{d && <>
      <section className="panel-card finance-metrics"><h2>Özet metrikler</h2><div className="finance-metric-grid">{[["Brüt satış",metrics.grossSalesMinor],["Net satış",metrics.netSalesMinor],["Eğitmen yükümlülüğü",metrics.trainerEarnedLiabilityMinor],["Fiziksel ürün maliyeti",metrics.physicalProductCostMinor],["Kargo maliyeti",metrics.shippingCostMinor]].map(([label,value])=><article key={label as string}><span>{label}</span><strong>{money(value as number)}</strong></article>)}</div></section>
      <section className="panel-card finance-table-card"><h2>Paket kârlılığı</h2>{d.packageProfitability?.length ? <div className="finance-table-wrap" tabIndex={0} role="region" aria-label="Paket kârlılığı tablosu; yatay kaydırılabilir"><table><thead><tr><th>Paket</th><th>Satış</th><th>Brüt gelir</th><th>İade</th><th>Eğitmen</th><th>Ürün</th><th>Kargo</th><th>Düzeltme</th><th>Katkı</th><th>Katkı %</th></tr></thead><tbody>{d.packageProfitability.map((row: any) => <tr key={`${row.packageId}-${row.currency}`}><td>{row.packageTitle}</td><td>{row.salesCount}</td><td>{money(row.grossRevenueMinor,row.currency)}</td><td>{money(row.refundsMinor,row.currency)}</td><td>{money(row.trainerCostMinor,row.currency)}</td><td>{money(row.physicalProductCostMinor,row.currency)}</td><td>{money(row.shippingCostMinor,row.currency)}</td><td>{money(row.adjustmentCostMinor,row.currency)}</td><td>{money(row.contributionMinor,row.currency)}</td><td>{row.contributionPercent}%</td></tr>)}</tbody></table></div> : <p>Seçili kapsamda paket satışı yok.</p>}</section>
      <section className="panel-card finance-table-card"><h2>Finans defteri</h2>{d.ledger.length ? <div className="finance-table-wrap" tabIndex={0} role="region" aria-label="Finans defteri tablosu; yatay kaydırılabilir"><table><thead><tr><th>Tarih</th><th>Tür</th><th>Kaynak</th><th>Tutar</th></tr></thead><tbody>{d.ledger.map((x: any, i: number) => <tr key={`${x.entryType}-${x.sourceId}-${x.currency}-${i}`}><td>{x.occurredAt ? new Date(x.occurredAt).toLocaleDateString("tr-TR") : "—"}</td><td>{entryLabels[x.entryType] || "Diğer işlem"}</td><td>{x.sourceId || "—"}</td><td>{money(x.amountMinor,x.currency)}</td></tr>)}</tbody></table></div> : <p>Henüz finans hareketi yok.</p>}</section><section className="panel-card finance-table-card"><h2>Eğitmen ödeme kayıtları</h2>{d.payouts.length ? <div className="finance-table-wrap" tabIndex={0} role="region" aria-label="Eğitmen ödeme kayıtları tablosu; yatay kaydırılabilir"><table><thead><tr><th>Eğitmen</th><th>Tutar</th></tr></thead><tbody>{d.payouts.map((x: any) => <tr key={`${x.trainerUserId}-${x.currency}`}><td>{x.trainerName || "Eğitmen"}</td><td>{money(x.paidMinor,x.currency)}</td></tr>)}</tbody></table></div> : <p>Henüz eğitmen ödeme kaydı yok.</p>}</section>
      <details className="panel-card finance-adjustment-details"><summary>Gelişmiş finans işlemleri</summary><p className="finance-adjustment-help"><strong>Manuel finans düzeltmesi</strong>, iade, istisnai ödeme veya muhasebe kaynaklı düzeltmeleri finans kaydına eklemek için kullanılır.</p><form className="admin-package-form finance-adjustment-form" onSubmit={(e) => void submit(e)}><label>Giriş türü<select value={adjustment.entryType} onChange={(e) => setAdjustment({ ...adjustment, entryType: e.target.value })}><option value="ADJUSTMENT">Düzeltme</option><option value="SALE">Satış</option><option value="REFUND">İade</option></select></label><label>Kaynak türü<select required value={adjustment.sourceType} onChange={(e) => setAdjustment({ ...adjustment, sourceType: e.target.value })}><option value="MANUAL">Manuel düzeltme</option><option value="REFUND">İade</option><option value="ACCOUNTING">Muhasebe düzeltmesi</option></select></label><label>Tutar (TL)<input required type="number" min="0" step="0.01" inputMode="decimal" value={adjustment.amountMinor ? (Number(adjustment.amountMinor)/100).toFixed(2) : ""} onChange={(e) => setAdjustment({ ...adjustment, amountMinor: String(Math.round(Number(e.target.value || 0) * 100)) })} /></label><label>Para birimi<input required maxLength={3} value={adjustment.currency} onChange={(e) => setAdjustment({ ...adjustment, currency: e.target.value.toUpperCase() })} /></label><label>Kaynak / Referans<input value={adjustment.sourceId} onChange={(e) => setAdjustment({ ...adjustment, sourceId: e.target.value })} /></label><label>Not<textarea value={adjustment.note} onChange={(e) => setAdjustment({ ...adjustment, note: e.target.value })} /></label><button type="submit">Düzeltmeyi kaydet</button></form></details>
    </>}</main>;
}
