import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import "./Giris.css";
import "./auth-lifecycle.css";

const roles = {
  STUDENT: { title: "Öğrenci Girişi", register: "/ogrenci-kayit" },
  TRAINER: { title: "Eğitmen Girişi", register: "/ogretmen-basvuru" },
  ADMIN: { title: "Yönetici Girişi" },
  OWNER: { title: "Sistem Sahibi Girişi" },
};
const Shell = ({ title, description, children }) => <main className="fixoku-login-page auth-lifecycle-page"><section className="fixoku-login-card auth-lifecycle-card"><div className="fixoku-login-logo"><img src="/siyah-logo-fixoku.png" alt="Fixoku" /></div><h1>{title}</h1>{description && <p>{description}</p>}{children}</section></main>;
const Message = ({ children, error = false }) => children ? <p className={error ? "auth-error" : "auth-message"} role={error ? "alert" : "status"}>{children}</p> : null;

export function RoleLoginPage({ role = "STUDENT" }) {
  const copy = roles[role] || roles.STUDENT; const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event) {
    event.preventDefault(); setBusy(true); setError("");
    try {
      const response = await fetch("/api/auth/sign-in/email", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify({ email: email.trim(), password }) });
      if (!response.ok) throw new Error(response.status === 401 ? "E-posta veya parola hatalı." : "Giriş tamamlanamadı.");
      const contextResponse = await fetch("/api/panel-context", { credentials: "same-origin" }); if (!contextResponse.ok) throw new Error("Oturum doğrulanamadı.");
      const context = await contextResponse.json(); const destination = context.destination || context.destinations?.[0] || "/panel";
      const expected = role === "ADMIN" ? ["OWNER", "SUPER_ADMIN"] : [role];
      if (!context.roles?.some((item) => expected.includes(item))) { setError("Bu hesap seçtiğiniz giriş alanına ait değil. Yetkili panele yönlendiriliyorsunuz."); setTimeout(() => navigate(destination, { replace: true }), 900); return; }
      navigate(destination, { replace: true });
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Giriş tamamlanamadı."); } finally { setBusy(false); }
  }
  return <Shell title={copy.title} description="Hesabınızla güvenli şekilde devam edin."><form onSubmit={submit} noValidate><label htmlFor="role-email">E-posta<input id="role-email" type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label htmlFor="role-password">Parola<input id="role-password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button type="submit" disabled={busy}>{busy ? "Giriş yapılıyor…" : "Giriş yap"}</button><Message error>{error}</Message></form><nav className="auth-links" aria-label="Hesap bağlantıları"><Link to="/sifremi-unuttum">Parolamı unuttum</Link>{copy.register && <Link to={copy.register}>{role === "STUDENT" ? "Öğrenci hesabı oluştur" : "Eğitmen başvurusu"}</Link>}<Link to="/giris">Diğer giriş seçenekleri</Link></nav></Shell>;
}

const studentFields = [["firstName", "Ad", "text"], ["lastName", "Soyad", "text"], ["email", "E-posta", "email"], ["phone", "Telefon", "tel"], ["password", "Parola", "password"], ["dateOfBirth", "Doğum tarihi", "date"], ["grade", "Sınıf", "text"], ["school", "Okul", "text"], ["schoolType", "Okul türü", "text"], ["city", "Şehir", "text"], ["district", "İlçe", "text"], ["guardianName", "Veli / yakın adı", "text"], ["guardianRelation", "Yakınlık", "text"], ["guardianPhone", "Veli telefonu", "tel"], ["guardianEmail", "Veli e-postası", "email"], ["addressLine", "Adres", "text"]];
export function StudentRegistrationPage() {
  const navigate = useNavigate(); const initial = Object.fromEntries(studentFields.map(([key]) => [key, ""])); const [form, setForm] = useState({ ...initial, terms: false, kvkk: false, marketingConsent: false }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = (key) => (e) => setForm((current) => ({ ...current, [key]: e.target.type === "checkbox" ? e.target.checked : e.target.value }));
  async function submit(event) { event.preventDefault(); if (!form.terms || !form.kvkk) { setError("Üyelik koşullarını ve KVKK aydınlatma metnini kabul etmeniz gerekir."); return; } setBusy(true); setError(""); try { const response = await fetch("/api/account-lifecycle/register", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(response.status === 422 ? "Bu e-posta ile zaten bir hesap olabilir." : "Kayıt tamamlanamadı."); navigate("/e-posta-dogrula", { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Kayıt tamamlanamadı."); } finally { setBusy(false); } }
  return <Shell title="Öğrenci Kaydı" description="Öğrenci hesabınız yalnızca Öğrenci yetkisiyle açılır."><form className="auth-registration-form" onSubmit={submit} noValidate>{studentFields.map(([key, label, type]) => <label key={key} htmlFor={"student-"+key}>{label}<input id={"student-"+key} type={type} value={form[key]} onChange={update(key)} required={["firstName", "lastName", "email", "phone", "password"].includes(key)} /></label>)}<label className="auth-check"><input type="checkbox" checked={form.terms} onChange={update("terms")} />Üyelik ve kullanım koşullarını kabul ediyorum.</label><label className="auth-check"><input type="checkbox" checked={form.kvkk} onChange={update("kvkk")} />KVKK aydınlatma metnini okudum.</label><label className="auth-check"><input type="checkbox" checked={form.marketingConsent} onChange={update("marketingConsent")} />Kampanya ve duyuruları almak istiyorum (isteğe bağlı).</label><button type="submit" disabled={busy}>{busy ? "Hesap oluşturuluyor…" : "Öğrenci hesabı oluştur"}</button><Message error>{error}</Message></form><p className="auth-secondary-link">Zaten hesabınız var mı? <Link to="/ogrenci-girisi">Öğrenci girişine dönün</Link></p></Shell>;
}

export function PasswordForgotPage() { const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(e) { e.preventDefault(); setBusy(true); try { const response = await fetch("/api/auth/request-password-reset", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify({ email: email.trim(), redirectTo: "/sifre-sifirla" }) }); setMessage(response.ok ? "Eğer bu e-posta ile kayıtlı bir hesap varsa şifre sıfırlama bağlantısı gönderildi." : "İstek şu anda tamamlanamadı."); } catch { setMessage("İstek şu anda tamamlanamadı."); } finally { setBusy(false); } } return <Shell title="Parolamı Unuttum" description="Hesabınıza ait e-posta adresini yazın."><form onSubmit={submit} noValidate><label htmlFor="forgot-email">E-posta<input id="forgot-email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><button type="submit" disabled={busy}>{busy ? "Gönderiliyor…" : "Sıfırlama bağlantısı gönder"}</button><Message>{message}</Message></form><p className="auth-secondary-link"><Link to="/giris">Giriş sayfasına dönün</Link></p></Shell>; }

export function PasswordResetPage() { const location = useLocation(); const navigate = useNavigate(); const token = new URLSearchParams(location.search).get("token") || ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(e) { e.preventDefault(); if (!token) return setMessage("Sıfırlama bağlantısı eksik veya geçersiz."); if (password.length < 8 || password !== confirm) return setMessage("Parola en az 8 karakter olmalı ve iki alan eşleşmelidir."); setBusy(true); try { const response = await fetch("/api/auth/reset-password", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", origin: window.location.origin }, body: JSON.stringify({ token, newPassword: password }) }); if (!response.ok) throw new Error("Sıfırlama bağlantısı geçersiz, süresi dolmuş veya daha önce kullanılmış."); setMessage("Parolanız yenilendi. Yeni parolanızla giriş yapabilirsiniz."); setTimeout(() => navigate("/giris", { replace: true }), 900); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Parola yenilenemedi."); } finally { setBusy(false); } } return <Shell title="Yeni Parola Belirle" description="Güvenliğiniz için yeni ve benzersiz bir parola seçin."><form onSubmit={submit} noValidate><label htmlFor="reset-password">Yeni parola<input id="reset-password" type="password" autoComplete="new-password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required /></label><label htmlFor="reset-confirm">Yeni parola (tekrar)<input id="reset-confirm" type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></label><button type="submit" disabled={busy}>{busy ? "Parola yenileniyor…" : "Parolayı yenile"}</button><Message>{message}</Message></form></Shell>; }

export function EmailVerificationPage() { const location = useLocation(); const navigate = useNavigate(); const token = new URLSearchParams(location.search).get("token") || ""; const [message, setMessage] = useState(token ? "E-posta adresiniz doğrulanıyor…" : "E-posta adresinizi doğrulamak için gelen bağlantıyı açın."); useEffect(() => { if (!token) return; let active = true; fetch("/api/auth/verify-email?token="+encodeURIComponent(token)+"&callbackURL=%2Fpanel", { credentials: "same-origin" }).then((r) => { if (!active) return; setMessage(r.ok ? "E-posta adresiniz doğrulandı. Panelinize yönlendiriliyorsunuz." : "Doğrulama bağlantısı geçersiz, süresi dolmuş veya daha önce kullanılmış."); if (r.ok) setTimeout(() => navigate("/panel", { replace: true }), 900); }).catch(() => active && setMessage("E-posta doğrulaması tamamlanamadı.")); return () => { active = false; }; }, [token, navigate]); return <Shell title="E-posta Doğrulama" description="Hesabınızı kullanmaya devam etmek için e-posta adresinizi doğrulayın."><Message>{message}</Message><p className="auth-secondary-link"><Link to="/giris">Giriş merkezine dönün</Link></p></Shell>; }

export function TrainerApplicationPage() { const [form, setForm] = useState({ name: "", email: "", phone: "", city: "", education: "", experience: "", requestedProgram: "", description: "", kvkk: false }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const update = (key) => (e) => setForm((current) => ({ ...current, [key]: e.target.type === "checkbox" ? e.target.checked : e.target.value })); async function submit(e) { e.preventDefault(); if (!form.kvkk) return setMessage("KVKK aydınlatma metnini kabul etmeniz gerekir."); setBusy(true); try { const r = await fetch("/api/trainer-applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); setMessage(r.ok ? "Başvurunuz alındı. İnceleme sonucu e-posta ile bildirilecektir." : "Başvurunuz kaydedilemedi."); } catch { setMessage("Başvurunuz kaydedilemedi."); } finally { setBusy(false); } } return <Shell title="Eğitmen Başvurusu" description="Başvurunuz incelenir; onay olmadan aktif eğitmen hesabı oluşturulmaz."><form className="auth-registration-form" onSubmit={submit} noValidate>{[["name", "Ad soyad"], ["email", "E-posta"], ["phone", "Telefon"], ["city", "Şehir"], ["education", "Mesleki / eğitim bilgileri"], ["experience", "Deneyim"], ["requestedProgram", "İlgilendiğiniz program"]].map(([key, label]) => <label key={key} htmlFor={"trainer-"+key}>{label}<input id={"trainer-"+key} type={key === "email" ? "email" : "text"} value={form[key]} onChange={update(key)} required={key !== "requestedProgram"} /></label>)}<label htmlFor="trainer-description">Açıklama<textarea id="trainer-description" value={form.description} onChange={update("description")} rows="4" /></label><label className="auth-check"><input type="checkbox" checked={form.kvkk} onChange={update("kvkk")} />KVKK aydınlatma metnini okudum.</label><button type="submit" disabled={busy}>{busy ? "Gönderiliyor…" : "Başvuruyu gönder"}</button><Message>{message}</Message></form><p className="auth-secondary-link"><Link to="/ogretmen-girisi">Eğitmen girişine dönün</Link></p></Shell>; }

export function AccountSecurityPage() { const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function change(e) { e.preventDefault(); if (newPassword.length < 8 || newPassword !== confirm) return setMessage("Yeni parola en az 8 karakter olmalı ve iki alan eşleşmelidir."); setBusy(true); try { const r = await fetch("/api/auth/change-password", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword, revokeOtherSessions: true }) }); setMessage(r.ok ? "Parolanız değiştirildi; diğer oturumlar kapatıldı." : "Parola değiştirilemedi."); } catch { setMessage("Parola değiştirilemedi."); } finally { setBusy(false); } } async function revoke() { setBusy(true); try { const r = await fetch("/api/auth/revoke-other-sessions", { method: "POST", credentials: "same-origin" }); setMessage(r.ok ? "Diğer oturumlar kapatıldı." : "Oturumlar kapatılamadı."); } catch { setMessage("Oturumlar kapatılamadı."); } finally { setBusy(false); } } return <Shell title="Hesap ve Güvenlik" description="Parolanızı ve açık oturumlarınızı yönetin."><form onSubmit={change} noValidate><label htmlFor="current-password">Mevcut parola<input id="current-password" type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} required /></label><label htmlFor="new-password">Yeni parola<input id="new-password" type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required /></label><label htmlFor="confirm-password">Yeni parola (tekrar)<input id="confirm-password" type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></label><button type="submit" disabled={busy}>Parolayı değiştir</button></form><button type="button" className="auth-secondary-button" onClick={() => void revoke()} disabled={busy}>Diğer oturumları kapat</button><Message>{message}</Message><p className="auth-secondary-link"><Link to="/panel">Panele dönün</Link></p></Shell>; }

export function InvitationAcceptPage({ kind = "trainer" }) {
  const location = useLocation(); const navigate = useNavigate(); const token = new URLSearchParams(location.search).get("token") || "";
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); if (!token) return setMessage("Davet bağlantısı eksik veya geçersiz."); if (password.length < 8 || password !== confirm) return setMessage("Parola en az 8 karakter olmalı ve alanlar eşleşmelidir."); setBusy(true); try { const response = await fetch(`/api/invitation-accept/${kind}-invitation-accept`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, email, name, password }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error === "INVITATION_INVALID_OR_USED" ? "Davet bağlantısı geçersiz, süresi dolmuş veya daha önce kullanılmış." : "Davet kabul edilemedi."); setMessage("Hesabınız etkinleştirildi. Giriş sayfasına yönlendiriliyorsunuz."); setTimeout(() => navigate(kind === "admin" ? "/admin-girisi" : "/ogretmen-girisi", { replace: true }), 700); } catch (error) { setMessage(error instanceof Error ? error.message : "Davet kabul edilemedi."); } finally { setBusy(false); } }
  return <Shell title={kind === "admin" ? "Yönetici davetini kabul et" : "Eğitmen hesabını etkinleştir"} description="Davet bağlantınız tek kullanımlıdır. Hesabınız için güvenli bir parola belirleyin."><form onSubmit={submit} noValidate><label htmlFor="invite-email">E-posta<input id="invite-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label htmlFor="invite-name">Ad soyad<input id="invite-name" value={name} onChange={(e) => setName(e.target.value)} required /></label><label htmlFor="invite-password">Parola<input id="invite-password" type="password" minLength={8} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><label htmlFor="invite-confirm">Parola (tekrar)<input id="invite-confirm" type="password" minLength={8} autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></label><button type="submit" disabled={busy}>{busy ? "Etkinleştiriliyor…" : "Daveti kabul et"}</button><Message>{message}</Message></form></Shell>;
}

export function AccountClosurePage() { const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function submit(e) { e.preventDefault(); setBusy(true); try { const response = await fetch("/api/account-lifecycle/closure", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason }) }); setMessage(response.ok ? "Hesap kapatma talebiniz kaydedildi." : "Talep gönderilemedi."); } catch { setMessage("Talep gönderilemedi."); } finally { setBusy(false); } } return <Shell title="Hesap kapatma talebi" description="Talebiniz operasyon ekibinin incelemesine iletilir. Kayıtlar, yasal saklama kurallarına göre korunur."><form onSubmit={submit} noValidate><label htmlFor="closure-reason">Neden (isteğe bağlı)<textarea id="closure-reason" rows="5" value={reason} onChange={(e) => setReason(e.target.value)} /></label><button type="submit" disabled={busy}>{busy ? "Gönderiliyor…" : "Hesap kapatma talebi gönder"}</button><Message>{message}</Message></form><p className="auth-secondary-link"><Link to="/hesap/guvenlik">Hesap güvenliğine dönün</Link></p></Shell>; }
export function TwoFactorPage() {
  const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [uri, setUri] = useState(""); const [busy, setBusy] = useState(false);
  async function requestUri(e) { e.preventDefault(); setBusy(true); try { const r = await fetch("/api/auth/two-factor/get-totp-uri", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error("2FA kurulumu başlatılamadı."); setUri(b.totpURI || ""); setMessage("Authenticator uygulamanızla QR kodu veya URI bilgisini kullanın."); } catch (e) { setMessage(e instanceof Error ? e.message : "2FA kurulumu başlatılamadı."); } finally { setBusy(false); } }
  async function verify(e) { e.preventDefault(); setBusy(true); try { const r = await fetch("/api/auth/two-factor/verify-totp", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ code, trustDevice: false }) }); if (!r.ok) throw new Error("Kod doğrulanamadı."); setMessage("İki aşamalı doğrulama etkinleştirildi."); } catch (e) { setMessage(e instanceof Error ? e.message : "Kod doğrulanamadı."); } finally { setBusy(false); } }
  async function backup() { setBusy(true); try { const r = await fetch("/api/auth/two-factor/generate-backup-codes", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error("Yedek kodlar üretilemedi."); setMessage(Array.isArray(b.backupCodes) ? `Yedek kodlar oluşturuldu (${b.backupCodes.length} adet). Güvenli bir yerde saklayın.` : "Yedek kodlar oluşturuldu."); } catch (e) { setMessage(e instanceof Error ? e.message : "Yedek kodlar üretilemedi."); } finally { setBusy(false); } }
  return <Shell title="İki aşamalı doğrulama" description="Yönetici ve sahip hesaplarında ek güvenlik katmanını yönetin."><form onSubmit={requestUri} noValidate><label htmlFor="twofactor-password">Mevcut parola<input id="twofactor-password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button type="submit" disabled={busy}>Kurulumu başlat</button></form>{uri && <div className="auth-message"><p>Kurulum URI'si yalnızca bu oturumda gösterilir.</p><code>{uri}</code><form onSubmit={verify}><label htmlFor="twofactor-code">Doğrulama kodu<input id="twofactor-code" inputMode="numeric" pattern="[0-9]{6}" value={code} onChange={(e) => setCode(e.target.value)} required /></label><button type="submit" disabled={busy}>Kodu doğrula</button></form></div>}<button type="button" className="auth-secondary-button" onClick={() => void backup()} disabled={busy}>Yedek kodları yenile</button><Message>{message}</Message><p className="auth-secondary-link"><Link to="/hesap/guvenlik">Hesap güvenliğine dönün</Link></p></Shell>;
}
