import pg from "pg";
import { resolvePrincipal, requirePermission } from "../../src/server/auth/authorization.js";

const json = (res, status, body) => { res.statusCode = status; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(body)); };
const headers = (req) => new Headers(Object.entries(req.headers || {}).map(([k, v]) => [k, Array.isArray(v) ? v.join(", ") : String(v)]));
const csvCell = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

function parseFilters(req) {
  const url = new URL(req.url || "/", "http://local");
  const from = url.searchParams.get("from") || ""; const to = url.searchParams.get("to") || ""; const packageId = url.searchParams.get("packageId") || ""; const trainerId = url.searchParams.get("trainerId") || ""; const currency = (url.searchParams.get("currency") || "").toUpperCase();
  if (from && !/^\d{4}-\d{2}-\d{2}$/u.test(from)) return { error: "INVALID_FROM_DATE" }; if (to && !/^\d{4}-\d{2}-\d{2}$/u.test(to)) return { error: "INVALID_TO_DATE" }; if (from && to && from > to) return { error: "INVALID_DATE_RANGE" }; if (currency && !/^[A-Z]{3}$/u.test(currency)) return { error: "INVALID_CURRENCY" }; if (packageId && !UUID.test(packageId)) return { error: "INVALID_PACKAGE_ID" }; if (trainerId && !UUID.test(trainerId)) return { error: "INVALID_TRAINER_ID" };
  return { from, to, packageId, trainerId, currency, format: url.searchParams.get("format") || "json" };
}

function orderScope(filters) {
  const values = []; const clauses = ["o.status IN ('PAID','PARTIALLY_REFUNDED','REFUNDED')"]; const add = (value, sql) => { values.push(value); clauses.push(sql.replace("$N", `$${values.length}`)); };
  if (filters.from) add(filters.from, "o.created_at >= $N::date"); if (filters.to) add(filters.to, "o.created_at < ($N::date + interval '1 day')"); if (filters.currency) add(filters.currency, "o.currency = $N"); if (filters.packageId) add(filters.packageId, "exists (select 1 from order_items f_oi where f_oi.order_id=o.id and f_oi.package_id=$N)"); if (filters.trainerId) add(filters.trainerId, "exists (select 1 from package_entitlement_enrollments f_pee join trainer_assignments f_ta on f_ta.enrollment_id=f_pee.enrollment_id where f_pee.source_order_item_id in (select oi.id from order_items oi where oi.order_id=o.id) and f_ta.trainer_user_id=$N)"); return { sql: clauses.join(" and "), values };
}

async function readFinance(pool, filters) {
  const scope = orderScope(filters); const ledgerClauses = []; const ledgerValues = []; const addLedger = (value, sql) => { ledgerValues.push(value); ledgerClauses.push(sql.replace("$N", `$${ledgerValues.length}`)); }; if (filters.from) addLedger(filters.from, "occurred_at >= $N::date"); if (filters.to) addLedger(filters.to, "occurred_at < ($N::date + interval '1 day')"); if (filters.currency) addLedger(filters.currency, "currency = $N"); const lp = ledgerClauses.length ? ` and ${ledgerClauses.join(" and ")}` : "";
  const earningClauses = []; const earningValues = []; const addEarning = (value, sql) => { earningValues.push(value); earningClauses.push(sql.replace("$N", `$${earningValues.length}`)); }; if (filters.trainerId) addEarning(filters.trainerId, "trainer_user_id = $N"); if (filters.packageId) addEarning(filters.packageId, "exists (select 1 from package_entitlement_enrollments f_pee join order_items f_oi on f_oi.id=f_pee.source_order_item_id where f_pee.enrollment_id=trainer_earning_ledger.enrollment_id and f_oi.package_id=$N)"); if (filters.from) addEarning(filters.from, "occurred_at >= $N::date"); if (filters.to) addEarning(filters.to, "occurred_at < ($N::date + interval '1 day')"); if (filters.currency) addEarning(filters.currency, "currency = $N"); const ep = earningClauses.length ? `where ${earningClauses.join(" and ")}` : "";
  const profitabilityTrainerClause = filters.trainerId ? ` and el.trainer_user_id=$${scope.values.length + 1}` : "";
  const profitabilityValues = filters.trainerId ? [...scope.values, filters.trainerId] : scope.values;
  const [ledger, payouts, sales, obligations, earningTotals, costs, packages, trainers, profitability] = await Promise.all([
    pool.query(`select entry_type as "entryType",source_type as "sourceType",source_id as "sourceId",currency,sum(amount_minor)::bigint as "amountMinor" from owner_finance_ledger where true${lp} group by entry_type,source_type,source_id,currency order by currency,entry_type`, ledgerValues),
    pool.query(`select trainer_user_id as "trainerUserId",u.display_name as "trainerName",currency,sum(amount_minor)::bigint as "paidMinor",count(*)::int as count from trainer_payout_register join platform_users u on u.id=trainer_user_id ${filters.currency ? "where currency=$1" : ""} group by trainer_user_id,u.display_name,currency order by u.display_name`, filters.currency ? [filters.currency] : []),
    pool.query(`select o.currency,count(*)::int as count,sum(o.total_minor)::bigint as "grossMinor",coalesce(sum((select sum(pt.amount_minor) from payment_intents pi join payment_transactions pt on pt.payment_intent_id=pi.id where pi.order_id=o.id and pt.transaction_type='REFUND' and pt.status='SUCCEEDED')),0)::bigint as "refundsMinor" from orders o where ${scope.sql} group by o.currency order by o.currency`, scope.values),
    pool.query("select count(*)::int as count from trainer_assignment_requests where status='PENDING'"),
    pool.query(`select currency,sum(case when status in ('EARNED','PAYABLE','HELD') then amount_minor else 0 end)::bigint as "earnedLiabilityMinor",sum(case when status='PAID' then amount_minor else 0 end)::bigint as "paidMinor" from trainer_earning_ledger ${ep} group by currency`, earningValues),
    pool.query(`select currency,sum(case when entry_type='SHIPPING_COST' then amount_minor else 0 end)::bigint as "shippingCostMinor",sum(case when entry_type='PHYSICAL_PRODUCT_COST' then amount_minor else 0 end)::bigint as "physicalProductCostMinor" from owner_finance_ledger where true${lp} group by currency`, ledgerValues),
    pool.query("select p.id as \"packageId\",coalesce(max(pv.title),p.slug) as \"title\" from packages p left join package_versions pv on pv.package_id=p.id where p.audience='STUDENT' group by p.id,p.slug order by \"title\""),
    pool.query("select distinct u.id as \"trainerId\",u.display_name as \"name\" from platform_users u join platform_memberships m on m.user_id=u.id where m.role='TRAINER' and m.status='ACTIVE' order by u.display_name"),
    pool.query(`select oi.package_id as "packageId",coalesce(max(pv.title),max(p.slug)) as "packageTitle",o.currency,count(distinct o.id)::int as "salesCount",sum(oi.total_minor)::bigint as "grossRevenueMinor",coalesce(sum((select sum(pt.amount_minor) from payment_intents pi join payment_transactions pt on pt.payment_intent_id=pi.id where pi.order_id=o.id and pt.transaction_type='REFUND' and pt.status='SUCCEEDED') * oi.total_minor / nullif(o.total_minor,0)),0)::bigint as "refundsMinor",coalesce(sum((select sum(el.amount_minor) from trainer_earning_ledger el join package_entitlement_enrollments pee on pee.enrollment_id=el.enrollment_id where pee.source_order_item_id=oi.id and el.currency=o.currency and el.status<>'REVERSED'${profitabilityTrainerClause})),0)::bigint as "trainerCostMinor",coalesce(sum((select sum(pp.cost_minor*si.quantity) from shipments s join shipment_items si on si.shipment_id=s.id join physical_products pp on pp.id=si.physical_product_id where s.order_id=o.id)),0)::bigint as "physicalProductCostMinor",coalesce(sum((select sum(coalesce(s.actual_shipping_cost_minor,s.shipping_charge_minor,0)) from shipments s where s.order_id=o.id)),0)::bigint as "shippingCostMinor",coalesce(sum((select sum(ofl.amount_minor) from owner_finance_ledger ofl where ofl.entry_type='ADJUSTMENT' and ofl.source_id=o.id::text and ofl.currency=o.currency)),0)::bigint as "adjustmentCostMinor" from order_items oi join orders o on o.id=oi.order_id join packages p on p.id=oi.package_id left join package_versions pv on pv.id=oi.package_version_id where ${scope.sql} group by oi.package_id,o.currency order by "packageTitle"`, profitabilityValues)
  ]);
  const salesRows = sales.rows.map((row) => ({ ...row, grossMinor: Number(row.grossMinor || 0), refundsMinor: Number(row.refundsMinor || 0), netMinor: Number(row.grossMinor || 0) - Number(row.refundsMinor || 0) })); const profitabilityRows = profitability.rows.map((row) => { const gross = Number(row.grossRevenueMinor || 0); const refunds = Number(row.refundsMinor || 0); const trainer = Number(row.trainerCostMinor || 0); const physical = Number(row.physicalProductCostMinor || 0); const shipping = Number(row.shippingCostMinor || 0); const adjustment = Number(row.adjustmentCostMinor || 0); const contribution = gross - refunds - trainer - physical - shipping - adjustment; return { ...row, grossRevenueMinor: gross, refundsMinor: refunds, trainerCostMinor: trainer, physicalProductCostMinor: physical, shippingCostMinor: shipping, adjustmentCostMinor: adjustment, contributionMinor: contribution, contributionPercent: gross ? Number((contribution * 100 / gross).toFixed(2)) : 0 }; }); const earnings = earningTotals.rows.find((row) => !filters.currency || row.currency === filters.currency) || {}; const cost = costs.rows.find((row) => !filters.currency || row.currency === filters.currency) || {}; const grossSales = salesRows.reduce((sum, row) => sum + row.grossMinor, 0); const refunds = salesRows.reduce((sum, row) => sum + row.refundsMinor, 0);
  return { ownerOnly: true, filters, packages: packages.rows, trainers: trainers.rows, ledger: ledger.rows.map((r) => ({ ...r, amountMinor: Number(r.amountMinor || 0) })), payouts: payouts.rows.map((r) => ({ ...r, paidMinor: Number(r.paidMinor || 0) })), sales: salesRows, packageProfitability: profitabilityRows, metrics: { grossSalesMinor: grossSales, netSalesMinor: grossSales - refunds, refundsMinor: refunds, shippingRevenueMinor: 0, shippingCostMinor: Number(cost.shippingCostMinor || 0), physicalProductCostMinor: Number(cost.physicalProductCostMinor || 0), trainerEarnedLiabilityMinor: Number(earnings.earnedLiabilityMinor || 0), trainerPaidMinor: Number(earnings.paidMinor || 0), trainerUnpaidMinor: Number(earnings.earnedLiabilityMinor || 0) - Number(earnings.paidMinor || 0) }, unfinishedTrainerLedObligations: Number(obligations.rows[0]?.count || 0) };
}

export default async function handler(req, res) {
  const principal = await resolvePrincipal(headers(req)); if (!principal) return json(res, 401, { error: "UNAUTHENTICATED" }); const denied = requirePermission(principal, req.method === "POST" ? "finance.adjust" : "finance.read"); if (denied) return json(res, denied.status, denied.body); const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  try { if (req.method === "POST") { let raw = ""; for await (const chunk of req) raw += chunk; const x = raw ? JSON.parse(raw) : {}; const amount = Number(x.amountMinor); const currency = String(x.currency || "TRY").toUpperCase(); if (!Number.isSafeInteger(amount) || amount === 0 || !/^[A-Z]{3}$/u.test(currency) || !String(x.entryType || "").trim() || !String(x.sourceType || "").trim()) return json(res, 400, { error: "ADJUSTMENT_VALIDATION_ERROR" }); const row = (await pool.query("insert into owner_finance_ledger(entry_type,source_type,source_id,amount_minor,currency,metadata_json,created_by) values($1,$2,$3,$4,$5,$6,$7) returning *", [String(x.entryType).trim(), String(x.sourceType).trim(), String(x.sourceId || "manual"), amount, currency, JSON.stringify({ note: String(x.note || "").slice(0, 500), manual: true }), principal.user.id])).rows[0]; return json(res, 201, { adjustment: row }); } if (req.method !== "GET") return json(res, 405, { error: "METHOD_NOT_ALLOWED" }); const filters = parseFilters(req); if (filters.error) return json(res, 400, { error: filters.error }); if (filters.format === "csv") { const data = await readFinance(pool, filters); const rows = [["section", "packageId", "packageTitle", "currency", "salesCount", "grossRevenueMinor", "refundsMinor", "trainerCostMinor", "physicalProductCostMinor", "shippingCostMinor", "adjustmentCostMinor", "contributionMinor", "contributionPercent"], ...data.packageProfitability.map((r) => ["package", r.packageId, r.packageTitle, r.currency, r.salesCount, r.grossRevenueMinor, r.refundsMinor, r.trainerCostMinor, r.physicalProductCostMinor, r.shippingCostMinor, r.adjustmentCostMinor, r.contributionMinor, r.contributionPercent])]; res.statusCode = 200; res.setHeader("Content-Type", "text/csv; charset=utf-8"); res.setHeader("Content-Disposition", 'attachment; filename="fixoku-finans.csv"'); res.setHeader("Cache-Control", "no-store"); return res.end(rows.map((row) => row.map(csvCell).join(",")).join("\n")); } return json(res, 200, await readFinance(pool, filters)); } catch (error) { console.error("FINANCE_UNAVAILABLE", error); return json(res, 503, { error: "FINANCE_UNAVAILABLE" }); } finally { await pool.end(); }
}
