import pg from "pg";
import { resolvePrincipal, requirePermission } from "../../src/server/auth/authorization.js";
const json=(res,status,body)=>{res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(body));};
const h=req=>new Headers(Object.entries(req.headers||{}).map(([k,v])=>[k,String(v)]));
async function read(req){let s="";for await(const c of req)s+=c;return s?JSON.parse(s):{};}
export default async function handler(req,res){
  const p=await resolvePrincipal(h(req));if(!p)return json(res,401,{error:"UNAUTHENTICATED"});const d=requirePermission(p,"payout.manage");if(d)return json(res,d.status,d.body);
  const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
  try{
    if(req.method==="GET"){const rows=(await pool.query("select * from trainer_payout_register order by payment_date desc,created_at desc")).rows;const accounts=(await pool.query("select trainer_user_id as \"trainerUserId\",account_holder_name as \"accountHolderName\",bank_name as \"bankName\",iban,note,updated_at as \"updatedAt\" from trainer_payout_accounts order by updated_at desc")).rows;return json(res,200,{payouts:rows,payoutAccounts:accounts,ownerOnly:true});}
    if(req.method!=="POST")return json(res,405,{error:"METHOD_NOT_ALLOWED"});
    const x=await read(req);const amount=Number(x.amountMinor);const currency=String(x.currency||"TRY").toUpperCase();
    if(!x.trainerUserId||!Number.isSafeInteger(amount)||amount<=0||!/^[A-Z]{3}$/u.test(currency)||!x.periodStart||!x.periodEnd||!x.paymentDate)return json(res,400,{error:"PAYOUT_FIELDS_REQUIRED"});
    const c=await pool.connect();try{await c.query("begin");const row=(await c.query("insert into trainer_payout_register(trainer_user_id,amount_minor,currency,period_start,period_end,payment_date,bank_reference,created_by,approved_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *",[x.trainerUserId,amount,currency,x.periodStart,x.periodEnd,x.paymentDate,x.bankReference||null,p.user.id,x.approvedBy||null])).rows[0];const paid=(await c.query("update trainer_earning_ledger set status='PAID',paid_at=now() where trainer_user_id=$1 and occurred_at::date between $2::date and $3::date and currency=$4 and status in ('EARNED','PAYABLE') returning id",[x.trainerUserId,x.periodStart,x.periodEnd,currency])).rows;await c.query("insert into owner_finance_ledger(entry_type,source_type,source_id,amount_minor,currency,metadata_json,created_by) values('TRAINER_PAYOUT','PAYOUT',$1,$2,$3,$4,$5)",[row.id,-amount,currency,JSON.stringify({trainerUserId:x.trainerUserId,periodStart:x.periodStart,periodEnd:x.periodEnd,earningIds:paid.map((item)=>item.id)}),p.user.id]);await c.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'trainer.payout.paid','trainer_payout',$2,'SUCCESS',gen_random_uuid(),$3)",[p.user.id,row.id,JSON.stringify({amountMinor:amount,currency,trainerUserId:x.trainerUserId,earningsMarkedPaid:paid.length})]);await c.query("commit");return json(res,201,{payout:row,status:"PAID",financeEntryCreated:true,earningsMarkedPaid:paid.length});}catch(e){try{await c.query("rollback")}catch{ /* preserve original error */ }return json(res,e.code==="23503"?409:503,{error:e.code==="23503"?"PAYOUT_REFERENCE_INVALID":"PAYOUT_UNAVAILABLE"});}finally{c.release();}
  }catch{return json(res,503,{error:"PAYOUT_UNAVAILABLE"});}finally{await pool.end();}
}
