import crypto from "node:crypto";
import pg from "pg";
import { resolvePrincipal, requirePermission } from "../../../src/server/auth/authorization.js";
import { UUID_PATTERN, normalizeCurrency } from "../../../src/server/domain/commerce.js";

const json = (res, status, body) => { res.statusCode = status; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(body)); };
const headers = (req) => new Headers(Object.entries(req.headers || {}).map(([key, value]) => [key, String(value)]));
async function readBody(req) { let raw = ""; for await (const chunk of req) raw += chunk; return raw ? JSON.parse(raw) : {}; }
function bad(code, status = 400) { return Object.assign(new Error(code), { status }); }
function fields(body) { const title = String(body.title || "").trim(); const slug = String(body.slug || "").trim().toLowerCase(); const description = String(body.description || "").trim(); const priceMinor = Number(body.priceMinor); const currency = normalizeCurrency(body.currency || "TRY"); const deliveryMode = String(body.deliveryMode || ""); const ids = Array.isArray(body.trainingProgramIds) ? [...new Set(body.trainingProgramIds.map(String))] : []; if (title.length < 2 || title.length > 180) throw bad("TITLE_REQUIRED"); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(slug)) throw bad("SLUG_INVALID"); if (!description || description.length > 4000) throw bad("DESCRIPTION_REQUIRED"); if (!Number.isSafeInteger(priceMinor) || priceMinor < 0) throw bad("PRICE_MINOR_INVALID"); if (!currency) throw bad("CURRENCY_INVALID"); if (!["SELF_PACED", "TRAINER_LED", "HYBRID"].includes(deliveryMode)) throw bad("DELIVERY_MODE_INVALID"); if (!ids.length || ids.some((id) => !UUID_PATTERN.test(id))) throw bad("TRAINING_PROGRAM_REQUIRED"); return { title, slug, description, priceMinor, currency, deliveryMode, ids }; }
async function validatePrograms(client, ids) { const rows = (await client.query("select id from training_programs where id=any($1::uuid[]) and audience='STUDENT' and status='PUBLISHED'", [ids])).rows; if (rows.length !== ids.length) throw bad("TRAINING_PROGRAM_UNAVAILABLE", 409); }
async function readPackage(client, id) { const rows = (await client.query("select p.id,p.slug,p.status as \"packageStatus\",p.created_at as \"createdAt\",p.updated_at as \"updatedAt\",pv.id as \"packageVersionId\",pv.version_number as \"versionNumber\",pv.title,pv.description,pv.price_minor as \"priceMinor\",pv.currency,pv.status as \"versionStatus\",ped.delivery_mode as \"deliveryMode\",ped.training_program_id as \"trainingProgramId\" from packages p left join package_versions pv on pv.package_id=p.id left join package_entitlement_definitions ped on ped.package_version_id=pv.id where p.id=$1 order by pv.version_number desc,ped.training_program_id", [id])).rows; if (!rows.length) throw bad("PACKAGE_NOT_FOUND", 404); const first = rows[0]; const result = { id: first.id, slug: first.slug, status: first.packageStatus, createdAt: first.createdAt, updatedAt: first.updatedAt, versions: [] }; for (const row of rows) { let version = result.versions.find((candidate) => candidate.id === row.packageVersionId); if (!version && row.packageVersionId) { version = { id: row.packageVersionId, versionNumber: row.versionNumber, title: row.title, description: row.description, priceMinor: row.priceMinor, currency: row.currency, status: row.versionStatus, deliveryMode: row.deliveryMode, trainingProgramIds: [] }; result.versions.push(version); } if (version && row.trainingProgramId && !version.trainingProgramIds.includes(row.trainingProgramId)) version.trainingProgramIds.push(row.trainingProgramId); } return result; }

export default async function handler(req, res) {
  const principal = await resolvePrincipal(headers(req)); if (!principal) return json(res, 401, { error: "UNAUTHENTICATED" }); const denied = requirePermission(principal, "package.manage"); if (denied) return json(res, denied.status, denied.body);
  const id = String(req.url || "").split("/").pop().split("?")[0]; if (!UUID_PATTERN.test(id)) return json(res, 400, { error: "INVALID_PACKAGE_ID" });
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL }); const client = await pool.connect();
  try {
    if (req.method === "GET") { const packageData = await readPackage(client, id); const programs = (await client.query("select id,title,slug from training_programs where audience='STUDENT' and status='PUBLISHED' order by display_order,id")).rows; return json(res, 200, { package: packageData, trainingPrograms: programs }); }
    if (!["PATCH", "POST"].includes(req.method)) return json(res, 405, { error: "METHOD_NOT_ALLOWED" });
    const body = await readBody(req); const action = String(body.action || "");
    if (req.method === "POST" && action === "publish") {
      await client.query("begin"); await client.query("select id from packages where id=$1 for update", [id]); const target = (await client.query("select * from package_versions where id=$1 and package_id=$2 for update", [body.versionId, id])).rows[0]; if (!target) throw bad("PACKAGE_VERSION_NOT_FOUND", 404); if (target.status !== "DRAFT") throw bad("PACKAGE_VERSION_NOT_DRAFT", 409); const defs = (await client.query("select training_program_id,delivery_mode from package_entitlement_definitions where package_version_id=$1", [target.id])).rows; if (!defs.length) throw bad("PACKAGE_DEFINITIONS_REQUIRED", 409); await validatePrograms(client, defs.map((row) => row.training_program_id)); await client.query("update package_versions set status='RETIRED',updated_at=now() where package_id=$1 and id<>$2 and status='PUBLISHED'", [id, target.id]); const published = (await client.query("update package_versions set status='PUBLISHED',published_at=now(),updated_at=now() where id=$1 returning *", [target.id])).rows[0]; await client.query("update packages set status='PUBLISHED',updated_at=now() where id=$1", [id]); await client.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'commerce.package.published','package_version',$2,'SUCCESS',$3,$4)", [principal.user.id, target.id, crypto.randomUUID(), JSON.stringify({ packageId: id, versionNumber: target.version_number })]); await client.query("commit"); return json(res, 200, { packageVersion: published, status: "PUBLISHED" });
    }
    if (req.method === "POST" && action === "retire") {
      await client.query("begin"); await client.query("select id from packages where id=$1 for update", [id]); const targetId = body.versionId || null; if (targetId && !UUID_PATTERN.test(String(targetId))) throw bad("INVALID_PACKAGE_VERSION_ID"); if (targetId) await client.query("update package_versions set status='RETIRED',updated_at=now() where id=$1 and package_id=$2", [targetId, id]); else await client.query("update package_versions set status='RETIRED',updated_at=now() where package_id=$1 and status in ('DRAFT','PUBLISHED')", [id]); const live = (await client.query("select count(*)::int as count from package_versions where package_id=$1 and status='PUBLISHED'", [id])).rows[0].count; if (Number(live) === 0) await client.query("update packages set status='RETIRED',updated_at=now() where id=$1", [id]); await client.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'commerce.package.retired','package',$2,'SUCCESS',$3,$4)", [principal.user.id, id, crypto.randomUUID(), JSON.stringify({ versionId: targetId })]); await client.query("commit"); return json(res, 200, { status: "RETIRED" });
    }
    if (req.method === "POST" && action === "createDraft") {
      await client.query("begin"); await client.query("select id from packages where id=$1 for update", [id]); const current = (await client.query("select * from package_versions where package_id=$1 order by version_number desc limit 1", [id])).rows[0]; if (!current) throw bad("PACKAGE_VERSION_NOT_FOUND", 404); const next = (await client.query("insert into package_versions(package_id,version_number,title,description,price_minor,currency,status) values($1,$2,$3,$4,$5,$6,'DRAFT') returning *", [id, current.version_number + 1, current.title, current.description, current.price_minor, current.currency])).rows[0]; await client.query("insert into package_entitlement_definitions(package_version_id,training_program_id,delivery_mode) select $1,training_program_id,delivery_mode from package_entitlement_definitions where package_version_id=$2", [next.id, current.id]); await client.query("update packages set updated_at=now() where id=$1", [id]); await client.query("commit"); return json(res, 201, { packageVersion: next });
    }
    if (req.method !== "PATCH") return json(res, 400, { error: "ACTION_REQUIRED" });
    const targetId = String(body.versionId || ""); if (!UUID_PATTERN.test(targetId)) return json(res, 400, { error: "PACKAGE_VERSION_REQUIRED" }); const next = fields(body); await client.query("begin"); const target = (await client.query("select * from package_versions where id=$1 and package_id=$2 for update", [targetId, id])).rows[0]; if (!target) throw bad("PACKAGE_VERSION_NOT_FOUND", 404); if (target.status !== "DRAFT") throw bad("PUBLISHED_VERSION_IMMUTABLE", 409); await validatePrograms(client, next.ids); await client.query("update packages set slug=$1,updated_at=now() where id=$2", [next.slug, id]); const updated = (await client.query("update package_versions set title=$1,description=$2,price_minor=$3,currency=$4,updated_at=now() where id=$5 returning *", [next.title, next.description, next.priceMinor, next.currency, targetId])).rows[0]; await client.query("delete from package_entitlement_definitions where package_version_id=$1", [targetId]); for (const programId of next.ids) await client.query("insert into package_entitlement_definitions(package_version_id,training_program_id,delivery_mode) values($1,$2,$3)", [targetId, programId, next.deliveryMode]); await client.query("insert into platform_audit_events(actor_user_id,action,subject_type,subject_id,result,correlation_id,metadata_json) values($1,'commerce.package.draft.updated','package_version',$2,'SUCCESS',$3,$4)", [principal.user.id, targetId, crypto.randomUUID(), JSON.stringify({ packageId: id })]); await client.query("commit"); return json(res, 200, { packageVersion: updated });
  } catch (cause) { try { await client.query("rollback"); } catch { /* noop */ } return json(res, cause.status || (cause.code === "23505" ? 409 : 400), { error: cause.code === "23505" ? "SLUG_ALREADY_EXISTS" : cause.message || "PACKAGE_MUTATION_FAILED" }); } finally { client.release(); await pool.end(); }
}
