import pg from "pg";
import { resolvePrincipal, requirePermission } from "../../src/server/auth/authorization.js";
import { listBeneficiaries, resolveBeneficiary, UUID_PATTERN } from "../../src/server/domain/commerce.js";

const json = (res, status, body) => { res.statusCode = status; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(body)); };
const headers = (req) => new Headers(Object.entries(req.headers || {}).map(([key, value]) => [key, String(value)]));

/** Backward-compatible catalog endpoint; entitlement states are server-derived. */
export default async function handler(req, res) {
  if (req.method !== "GET") return json(res, 405, { error: "METHOD_NOT_ALLOWED" });
  const principal = await resolvePrincipal(headers(req)); if (!principal) return json(res, 401, { error: "UNAUTHENTICATED" }); const denied = requirePermission(principal, "package.read"); if (denied) return json(res, denied.status, denied.body);
  const role = principal.memberships.some((membership) => membership.role === "GUARDIAN") ? "GUARDIAN" : principal.memberships.find((membership) => membership.role === "STUDENT")?.role; if (!role) return json(res, 403, { error: "FORBIDDEN" });
  const requested = new URL(req.url, "http://local").searchParams.get("studentProfileId"); if (requested && !UUID_PATTERN.test(requested)) return json(res, 403, { error: "FORBIDDEN" }); const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  try { const students = await listBeneficiaries(pool, principal); const beneficiary = await resolveBeneficiary(pool, principal, requested || null); const rows = (await pool.query("select p.slug,p.status as \"packageStatus\",pv.id as \"packageVersionId\",pv.package_id as \"packageId\",pv.version_number as \"versionNumber\",pv.title,pv.description,pv.price_minor as \"priceMinor\",pv.currency,pv.status as \"versionStatus\",ped.delivery_mode as \"deliveryMode\",pe.id as \"entitlementId\",pe.status as \"entitlementStatus\",po.id as \"pendingOrderId\" from package_versions pv join packages p on p.id=pv.package_id left join package_entitlement_definitions ped on ped.package_version_id=pv.id left join lateral (select pe1.id,pe1.status from package_entitlements pe1 where pe1.package_version_id=pv.id and pe1.beneficiary_student_user_id=$1 order by case when pe1.status='ACTIVE' then 0 else 1 end,pe1.effective_at desc limit 1) pe on true left join lateral (select o.id from orders o join order_items oi on oi.order_id=o.id where o.beneficiary_student_user_id=$1 and o.status='PENDING_PAYMENT' and oi.package_version_id=pv.id order by o.created_at desc limit 1) po on true where p.audience='STUDENT' and ((pv.status='PUBLISHED' and p.status='PUBLISHED') or pe.id is not null) and (pe.id is not null or (not exists (select 1 from package_entitlements pe2 where pe2.package_id=p.id) and p.slug not like 'phase2b-%' and p.slug not like 'demo-003d-%')) order by pv.title,pv.version_number desc", [beneficiary.studentUserId])).rows; const map = new Map(); for (const row of rows) { const state = row.entitlementStatus === "ACTIVE" ? "OWNED" : row.entitlementStatus === "REVOKED" ? "REVOKED" : row.entitlementStatus === "EXPIRED" ? "EXPIRED" : row.pendingOrderId ? "PENDING_PAYMENT" : "AVAILABLE"; const current = map.get(row.packageVersionId); if (!current) map.set(row.packageVersionId, { ...row, id: row.packageVersionId, deliveryMode: row.deliveryMode || "SELF_PACED", accessState: state }); else if (row.deliveryMode && current.deliveryMode !== row.deliveryMode) current.deliveryMode = "HYBRID"; } return json(res, 200, { role, context: role === "GUARDIAN" ? { studentProfileId: beneficiary.studentProfileId, studentName: beneficiary.studentName } : null, beneficiary: { studentProfileId: beneficiary.studentProfileId, studentUserId: beneficiary.studentUserId }, students: role === "GUARDIAN" ? students.map(({ studentProfileId, studentName }) => ({ studentProfileId, name: studentName })) : [], packages: [...map.values()] }); } catch (cause) { return json(res, cause.status || 503, { error: cause.code || cause.message || "PACKAGES_UNAVAILABLE" }); } finally { await pool.end(); }
}
