import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PanelIcon } from "../../panel/components/PanelIcon";
import { PanelShell } from "../../panel/layout/PanelShell";
import type { TrainerStudent } from "./TrainerStudentsPage";
import "./trainer-students.css";

export function TrainerStudentDetailPage({ user }: { user: { id: string; name: string; email: string } }) {
  const { id } = useParams<{ id: string }>(); const [student, setStudent] = useState<TrainerStudent | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = useCallback(async () => { if (!id) { setState("error"); return; } setState("loading"); try { const response = await fetch(`/api/trainer/students/${encodeURIComponent(id)}`, { credentials: "same-origin" }); if (!response.ok) throw new Error(); const body = (await response.json()) as { student?: TrainerStudent }; if (!body.student) throw new Error(); setStudent(body.student); setState("ready"); } catch { setState("error"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const enrollment = student?.enrollments?.[0]; const status = student?.status ?? "ACTIVE";
  return <PanelShell user={user}><main className="trainer-students-page student-detail-page"><p className="students-breadcrumb"><Link to="/panel/egitmen">Ana Sayfa</Link><span aria-hidden="true">›</span><Link to="/panel/egitmen/ogrencilerim">Öğrencilerim</Link><span aria-hidden="true">›</span> Öğrenci Detayı</p><div className="detail-heading"><div><h2>Öğrenci Detayı</h2><p>Öğrenci bilgilerini ve eğitim planını bu sayfada görüntüleyebilirsiniz.</p></div><Link className="back-students" to="/panel/egitmen/ogrencilerim"><span aria-hidden="true">←</span> Öğrencilerime Dön</Link></div>
    {state === "loading" && <div className="students-state" role="status" aria-live="polite"><span className="loading-dot" /> Öğrenci yükleniyor…</div>}{state === "error" && <div className="students-state" role="alert"><h3>Öğrenci bulunamadı</h3><p>Bu öğrenci size bağlı olmayabilir veya erişim geçici olarak kullanılamıyor.</p><button type="button" onClick={() => void load}>Tekrar dene</button></div>}{state === "ready" && student && <>
      <section className="student-detail-card" aria-labelledby="student-detail-name"><div className="detail-avatar" aria-hidden="true">{student.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div className="detail-identity"><h3 id="student-detail-name">{student.name}</h3><p>{student.grade ?? "Seviye belirtilmedi"}<span aria-hidden="true"> | </span>{student.school ?? "Okul belirtilmedi"}</p><small>{student.email}</small></div><div className="detail-meta"><span>Aldığı Eğitim<strong>{enrollment?.programTitle ?? "Henüz tanımlanmadı"}</strong></span><span>Durum<strong className={`student-status status-${status.toLowerCase()}`}><i />{status === "ACTIVE" ? "Aktif" : status}</strong></span></div></section>
      <section className="detail-info-card" aria-labelledby="guardian-heading"><h3 id="guardian-heading"><PanelIcon name="user" size={22} /> Veli Bilgileri</h3><p>Veli iletişim bilgileri bu aşamada paylaşılmıyor.</p></section><section className="detail-info-card" aria-labelledby="plan-heading"><h3 id="plan-heading"><PanelIcon name="calendar" size={22} /> Eğitim Planı</h3><p>{enrollment ? "Eğitim planının ayrıntıları tanımlandığında burada görüntülenecek." : "Planlanan eğitim bilgileri tanımlandığında burada görüntülenecek."}</p></section><section className="detail-deferred-card" aria-label="Öğrenci gelişimi"><h3>Öğrenci gelişimi</h3><p>İlerleme, devam ve not bilgileri ilgili eğitim alanı tamamlandığında burada yer alacak.</p><span>İlerleme alanı sonraki fazda açılacak.</span></section>
    </>}</main></PanelShell>;
}
